<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../FoulFilterNet.Domain/FoulFilterNet.Domain.csproj" />
    <ProjectReference Include="../FoulFilterNet.Pipeline/FoulFilterNet.Pipeline.csproj" />
    <ProjectReference Include="../FoulFilterNet.Jobs/FoulFilterNet.Jobs.csproj" />
  </ItemGroup>

</Project>
